version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/frontend
      - ./node_modules:/front-end/node_modules
    command: ["npm", "run", "dev"]