stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  image: node:20.17-alpine 
  cache:
    paths:
      - .frontend/node_modules/
      - .frontend/.next/cache/
  script:
    - echo "Compiling the code..."
    - cd frontend
    - npm install
    - npm run build
    - echo "Compile complete."

postman-test-job:
  stage: test
  image: postman/newman:alpine
  script:
    - echo "Running Postman tests..."
    - newman run PalestineWatch.postman_collection.json
    - echo "Postman tests complete."

unit-test-job:
  stage: test
  image: node:20-alpine
  script:
    - echo "Running Jest tests..."
    - cd frontend # Navigate to the front-end directory
    - npm install # Install dependencies
    - npm test # Run Jest tests
    - echo "Jest tests complete."

selenium-test-job:
  stage: test
  image: python:3.8
  services:
    - name: selenium/standalone-chrome:latest
      alias: selenium
  script:
    - echo "Running Selenium tests..."
    - pip install selenium webdriver-manager
    - python -m unittest discover -s frontend/__test__ -p "acceptance-tests.py" -v
    - echo "Selenium tests complete."


api-test-job:
  stage: test
  image: python:latest
  script:
    - echo "Running API tests..."
	- cd backend
	- python -m unit_tests.unit-test
    - echo "API tests complete."
