version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5001:5000"  # Make sure this port is available
    volumes:
      - .:/back-end
    env_file:
      - .flaskenv
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres  # Optional: specify the PostgreSQL user
      POSTGRES_PASSWORD: downingswepalestinewatch  # Set your desired password
      POSTGRES_DB: PalestineWatchDB  # Optional: specify the database name
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
