"""Initial migration.

Revision ID: 35e1b7890524
Revises: 
Create Date: 2024-10-22 11:27:50.338413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35e1b7890524'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag_url', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('capital', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('population', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('region', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('subregion', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('common_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('official_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('unMembership', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('maps', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('newsId', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('supportGroupId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'support_groups', ['supportGroupId'], ['id'])
        batch_op.create_foreign_key(None, 'news', ['newsId'], ['id'])

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('supportGroupId',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('countryId',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('support_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('newsId', sa.Integer(), nullable=True))
        batch_op.alter_column('countryId',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('support_groups_newId_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'news', ['newsId'], ['id'])
        batch_op.drop_column('newId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('newId', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('support_groups_newId_fkey', 'news', ['newId'], ['id'])
        batch_op.alter_column('countryId',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('newsId')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('countryId',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('supportGroupId',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('supportGroupId')
        batch_op.drop_column('newsId')
        batch_op.drop_column('maps')
        batch_op.drop_column('unMembership')
        batch_op.drop_column('official_name')
        batch_op.drop_column('common_name')
        batch_op.drop_column('subregion')
        batch_op.drop_column('region')
        batch_op.drop_column('population')
        batch_op.drop_column('capital')
        batch_op.drop_column('flag_url')

    # ### end Alembic commands ###
